version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tiilted
      MYSQL_DATABASE: test
    ports:
      - 3366:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
